version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      - FRONTEND_URL=http://localhost:3000
      - API_URL=http://localhost:4000